export const HEADER_ORDERS = [
    { id: 'h1', text: '' },
    { id: 'h2', text: '№' },
    { id: 'h3', text: 'Номер заказа', key: 'numberOrder' },
    { id: 'h4', text: 'Проект', key: 'project' },
    { id: 'h5', text: 'ФИО', key: 'fio' },
    { id: 'h6', text: 'Телефон', sort: false, activeSort: false, key: null },
    { id: 'h7', text: 'Сумма заказа', align: 'right', key: 'sumOrder' },
    { id: 'h8', text: 'Комментарий', key: 'comment' },
    { id: 'h9', text: 'Дата посылки', key: 'dataPackage' },
    { id: 'h10', text: 'Вид доставки', align: 'center', key: 'typeTransfer' },
    { id: 'h11', text: 'Вскрытие получаетелем', align: 'center', key: 'openingStatus' },
    { id: 'h12', text: 'Стоимость доставки', align: 'right', key: 'deliverySum' },
    { id: 'h13', text: 'Оплата доставки', align: 'right', key: 'paySum' },
    { id: 'h14', text: 'Объявленная стоимость', align: 'right', key: 'declaredSum' },
    { id: 'h15', text: 'Код пункта поступления', align: 'center', key: 'departurePointCode' },
    { id: 'h16', text: 'Код ПВЗ', key: 'codePWZ', align: 'center' },
    { id: 'h17', text: 'Вес 1 места (грамм)', key: 'weightPackage' },
    { id: 'h18', text: 'Текст Ошибки' },
    { id: 'h19', text: '' },
    { id: 'h20', text: '' },
]